<script context="module">
  export async function preload({ params }) {
    try {
      // As with the server route, we have acces to params.slug here
      const res = await this.fetch(`api/blog/frontpage`);
      const { frontpage } = await res.json();
      return { frontpage };
    } catch (err) {
      this.error(500, err);
    }
  };
</script>
<script>
  import BlockContent from "@movingbrands/svelte-portable-text";
  import serializers from "../components/serializers";

  export let frontpage;
</script>
<style>
	h1, figure, p {
		text-align: center;
		margin: 0 auto;
	}

	h1 {
		font-size: 2.8em;
		text-transform: uppercase;
		font-weight: 700;
		margin: 0 0 0.5em 0;
	}

	figure {
		margin: 0 0 1em 0;
	}

	svg {
		width: 100%;
		max-width: 400px;
		margin: 0 0 1em 0;
	}

	p {
		margin: 1em auto;
	}

	@media (min-width: 480px) {
		h1 {
			font-size: 4em;
		}
	}
</style>

<svelte:head>
	<title>{frontpage[0].name}</title>
</svelte:head>

<h1>{frontpage[0].name}</h1>
<map name="image-map">
    <area alt="4" title="4" href="4.html" coords="514,1082,248" shape="circle">
</map>
<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="https://cdn.sanity.io/images/i4hcircn/production/870738e5664bca8d606c7038619ca3fba516ff6d-4000x3000.jpg?w=800&auto=format" usemap="#image-map">



<div class="content">
  <BlockContent blocks={frontpage[0].image} {serializers} />
   <BlockContent blocks={frontpage[0].bio} {serializers} />
</div>